name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Python3
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      
      - name: Cache files
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install \
               mkdocs \
               mkdocs-material \
               mkdocs-static-i18n \
               mkdocs-git-revision-date-localized-plugin \
               typing-extensions

      - run: mkdocs gh-deploy --force
